actual_features:
  - has_https
  - url_len
  - domain_len
  - path_len
  - query_len
  - url_depth
  - subdomain_count
  - tld_len
  - sld_len
  - sld_has_digit
  - sld_has_hyphen
  - dot_count_domain
  - hyphen_count_domain_path
  - underscore_count_path_query
  - slash_count
  - digit_count
  - alphabet_count
  - spl_char_count
  - url_entropy
  - domain_entropy
  - sld_entropy
  - path_entropy
  - domain_token_count
  - path_token_count
  - avg_token_length
  - label

active_features:
  - has_https
  - url_len
  - domain_len
  - path_len
  - query_len
  - url_depth
  - subdomain_count
  - tld_len
  - sld_len
  - sld_has_digit
  - sld_has_hyphen
  - dot_count_domain
  - hyphen_count_domain_path
  - underscore_count_path_query
  - slash_count
  - digit_count
  - alphabet_count
  - spl_char_count
  - url_entropy
  - domain_entropy
  - sld_entropy
  - path_entropy
  - domain_token_count
  - path_token_count
  - avg_token_length
  - label